### ISSUE TITLE
Console Spam from CSCoreLib2

### ISSUE THREAD

**Issue by samidont0817** [TheBusyBiscuit/CS-CoreLib2#82]
## Description (Required)
While Android Owner is online everything works fine and does not spam console. As soon as the owner logs off and the android is still being loaded it spams console with what is at the bottom of the pastebin under Server Log/Error Report

## Steps to reproduce the Issue (Required)
Android Owner sets up android, logs off but keep android loaded by someone else, console gets spammed

## Expected behavior (Required)
Expect androids not spamming console when owner is offline, and android is loaded

## Server Log / Error Report
https://pastebin.com/YnuKyemf
## Server specs (Required)
Paper(245) 1.15.2-R0.1-SNAPSHOT

 - Server Software: Paper
 - Minecraft Version: 1.15.2

## FULL plugins list (Required)
https://pastebin.com/y4WcZCWt

**Comment by TheBusyBiscuit** [comment]
The bug stems from the fact that WorldGuard supports Offline Players (like Androids) and it uses WorldEdit's core methods to do so.
However... you are not using WorldEdit, you are using FAWE which does not support Offline Players at the moment and instead throws a NullPointerException if the Player is offline.

This should be fixed on FAWE's part since WorldGuard and WorldEdit both have this support, so the API's component contract should be respected.
A temporary fix for this would be to use WorldEdit instead since WorldEdit works flawlessly.
